/* Claude Arc Games — master list of all games.
   category must be one of: arcade, puzzle, cards, trivia, skill
   multiplayer:true means the game has a real-time friend-vs-friend mode via friends.js */
window.ARCADE_GAMES = [
  { slug: "snake", title: "Snake", icon: "🐍", category: "arcade" },
  { slug: "pong", title: "Pong", icon: "🏓", category: "arcade" },
  { slug: "breakout", title: "Breakout", icon: "🧱", category: "arcade" },
  { slug: "space-invaders", title: "Space Invaders", icon: "👾", category: "arcade" },
  { slug: "asteroid-dodge", title: "Asteroid Dodge", icon: "☄️", category: "arcade" },
  { slug: "flappy-bird", title: "Flappy Bird", icon: "🐦", category: "arcade" },
  { slug: "doodle-jump", title: "Doodle Jump", icon: "🦘", category: "arcade" },
  { slug: "whack-a-mole", title: "Whack-a-Mole", icon: "🔨", category: "skill" },
  { slug: "plinko", title: "Plinko", icon: "🔴", category: "arcade" },
  { slug: "fruit-catcher", title: "Fruit Catcher", icon: "🍎", category: "arcade" },
  { slug: "simon-says", title: "Simon Says", icon: "🎵", category: "skill" },
  { slug: "reaction-time", title: "Reaction Time", icon: "⚡", category: "skill" },
  { slug: "typing-speed", title: "Typing Speed Test", icon: "⌨️", category: "skill" },
  { slug: "maze-runner", title: "Maze Runner", icon: "🌀", category: "arcade" },
  { slug: "platform-jump", title: "Platform Jump", icon: "🏃", category: "arcade" },
  { slug: "neon-brick-breaker", title: "Neon Brick Breaker", icon: "💡", category: "arcade" },
  { slug: "air-hockey", title: "Air Hockey", icon: "🏒", category: "arcade" },
  { slug: "target-shooter", title: "Target Shooter", icon: "🎯", category: "skill" },
  { slug: "balloon-pop", title: "Balloon Pop", icon: "🎈", category: "skill" },
  { slug: "frog-crossing", title: "Frog Crossing", icon: "🐸", category: "arcade" },
  { slug: "tic-tac-toe", title: "Tic Tac Toe", icon: "❌", category: "puzzle", multiplayer: true },
  { slug: "connect-four", title: "Connect Four", icon: "🔵", category: "puzzle" },
  { slug: "memory-match", title: "Memory Match", icon: "🃏", category: "puzzle" },
  { slug: "2048", title: "2048", icon: "🔢", category: "puzzle" },
  { slug: "minesweeper", title: "Minesweeper", icon: "💣", category: "puzzle" },
  { slug: "sliding-puzzle", title: "Sliding Puzzle", icon: "🧩", category: "puzzle" },
  { slug: "sudoku", title: "Sudoku", icon: "🔣", category: "puzzle" },
  { slug: "tower-of-hanoi", title: "Tower of Hanoi", icon: "🗼", category: "puzzle" },
  { slug: "mastermind", title: "Mastermind", icon: "🧠", category: "puzzle" },
  { slug: "nonogram", title: "Nonogram", icon: "▦", category: "puzzle" },
  { slug: "word-search", title: "Word Search", icon: "🔍", category: "trivia" },
  { slug: "crossword-mini", title: "Mini Crossword", icon: "📝", category: "trivia" },
  { slug: "anagram-solver", title: "Anagram Challenge", icon: "🔤", category: "trivia" },
  { slug: "word-scramble", title: "Word Scramble", icon: "🔀", category: "trivia" },
  { slug: "hangman", title: "Hangman", icon: "🎪", category: "trivia" },
  { slug: "wordle-clone", title: "Wordle", icon: "🟩", category: "trivia" },
  { slug: "match-three", title: "Match Three", icon: "💎", category: "puzzle" },
  { slug: "lights-out", title: "Lights Out", icon: "💡", category: "puzzle" },
  { slug: "peg-solitaire", title: "Peg Solitaire", icon: "⚪", category: "puzzle" },
  { slug: "color-slider", title: "Color Slider", icon: "🎨", category: "puzzle" },
  { slug: "nim", title: "Nim", icon: "🪵", category: "puzzle" },
  { slug: "dots-and-boxes", title: "Dots and Boxes", icon: "▫️", category: "puzzle" },
  { slug: "battleship", title: "Battleship", icon: "🚢", category: "puzzle" },
  { slug: "checkers", title: "Checkers", icon: "⚫", category: "puzzle" },
  { slug: "chess-vs-ai", title: "Chess vs CPU", icon: "♟️", category: "puzzle" },
  { slug: "reversi", title: "Reversi", icon: "⚪", category: "puzzle" },
  { slug: "klondike-solitaire", title: "Klondike Solitaire", icon: "🂡", category: "cards" },
  { slug: "spider-solitaire", title: "Spider Solitaire", icon: "🕷️", category: "cards" },
  { slug: "freecell", title: "FreeCell", icon: "🃁", category: "cards" },
  { slug: "pyramid-solitaire", title: "Pyramid Solitaire", icon: "🔺", category: "cards" },
  { slug: "blackjack", title: "Blackjack", icon: "🂱", category: "cards" },
  { slug: "war-card-game", title: "War", icon: "⚔️", category: "cards" },
  { slug: "higher-lower", title: "Higher or Lower", icon: "⬆️", category: "cards" },
  { slug: "poker-draw", title: "Five Card Draw", icon: "🂮", category: "cards" },
  { slug: "uno-lite", title: "Uno Lite", icon: "🔴", category: "cards" },
  { slug: "yahtzee-lite", title: "Yahtzee", icon: "🎲", category: "cards" },
  { slug: "farkle-lite", title: "Farkle", icon: "🎲", category: "cards" },
  { slug: "dice-predict", title: "Dice Prediction", icon: "🎲", category: "cards" },
  { slug: "coin-flip-streak", title: "Coin Flip Streak", icon: "🪙", category: "cards" },
  { slug: "slot-machine", title: "Slot Machine", icon: "🎰", category: "cards" },
  { slug: "roulette-lite", title: "Roulette", icon: "🎡", category: "cards" },
  { slug: "craps-lite", title: "Craps", icon: "🎲", category: "cards" },
  { slug: "rock-paper-scissors", title: "Rock Paper Scissors", icon: "✂️", category: "skill" },
  { slug: "rps-lizard-spock", title: "RPS Lizard Spock", icon: "🦎", category: "skill" },
  { slug: "guess-the-number", title: "Guess the Number", icon: "🔢", category: "trivia" },
  { slug: "lucky-wheel", title: "Lucky Wheel", icon: "🎡", category: "cards" },
  { slug: "math-addition-drill", title: "Addition Drill", icon: "➕", category: "trivia" },
  { slug: "math-subtraction-drill", title: "Subtraction Drill", icon: "➖", category: "trivia" },
  { slug: "math-multiplication-drill", title: "Multiplication Drill", icon: "✖️", category: "trivia" },
  { slug: "math-division-drill", title: "Division Drill", icon: "➗", category: "trivia" },
  { slug: "trivia-general", title: "General Trivia", icon: "❓", category: "trivia" },
  { slug: "trivia-science", title: "Science Trivia", icon: "🔬", category: "trivia" },
  { slug: "trivia-geography", title: "Geography Trivia", icon: "🌍", category: "trivia" },
  { slug: "trivia-history", title: "History Trivia", icon: "📜", category: "trivia" },
  { slug: "trivia-movies", title: "Movie Trivia", icon: "🎬", category: "trivia" },
  { slug: "word-association", title: "Word Association", icon: "🔗", category: "trivia" },
  { slug: "rhyme-time", title: "Rhyme Time", icon: "🎤", category: "trivia" },
  { slug: "emoji-guess", title: "Emoji Guess", icon: "😀", category: "trivia" },
  { slug: "flag-quiz", title: "Flag Quiz", icon: "🚩", category: "trivia" },
  { slug: "capital-cities-quiz", title: "Capital Cities Quiz", icon: "🏛️", category: "trivia" },
  { slug: "spelling-bee", title: "Spelling Bee", icon: "🐝", category: "trivia" },
  { slug: "vocabulary-quiz", title: "Vocabulary Quiz", icon: "📚", category: "trivia" },
  { slug: "color-match-stroop", title: "Color Match", icon: "🌈", category: "skill" },
  { slug: "pattern-memory", title: "Pattern Memory", icon: "🧩", category: "skill" },
  { slug: "number-memory", title: "Number Memory", icon: "🔢", category: "skill" },
  { slug: "fast-click-challenge", title: "Fast Click Challenge", icon: "🖱️", category: "skill" },
  { slug: "aim-trainer", title: "Aim Trainer", icon: "🎯", category: "skill" },
  { slug: "timing-bar", title: "Timing Bar", icon: "📊", category: "skill" },
  { slug: "balance-ball", title: "Balance Ball", icon: "⚖️", category: "skill" },
  { slug: "bubble-pop", title: "Bubble Pop", icon: "🫧", category: "skill" },
  { slug: "fruit-slice", title: "Fruit Slice", icon: "🍉", category: "skill" },
  { slug: "tetris-lite", title: "Tetris Lite", icon: "🟦", category: "arcade" },
  { slug: "pacman-lite", title: "Pac-Chomp", icon: "🟡", category: "arcade" },
  { slug: "tank-battle", title: "Tank Battle", icon: "🛡️", category: "arcade" },
  { slug: "basketball-shootout", title: "Basketball Shootout", icon: "🏀", category: "skill" },
  { slug: "golf-putt", title: "Mini Golf Putt", icon: "⛳", category: "skill" },
  { slug: "archery-target", title: "Archery Target", icon: "🏹", category: "skill" },
  { slug: "car-dodge", title: "Car Dodge", icon: "🚗", category: "arcade" },
  { slug: "endless-runner", title: "Endless Runner", icon: "🏃‍♂️", category: "arcade" },
  { slug: "bubble-shooter", title: "Bubble Shooter", icon: "🔵", category: "arcade" }
];
